server:
  port: ${PORT:8081}
  servlet:
    context-path: /edd

spring:
  application:
    name: omoc.edd.api
  profiles:
    active: ${ACTIVE:local}

logging:
  path: logs
  level:
    ROOT: ${ROOT:INFO}
  pattern:
    level: '%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId:-},%X{spanId:-},%X{X-Span-Export:-}]'
